# Generated by Django 4.0.1 on 2022-08-25 10:30

from django.db import migrations
from ..initial_perms import populate_groups

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(populate_groups)
    ]
