version: "3.8"
services: 
  PP2DB:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: django_db_user
      POSTGRES_PASSWORD: Password123
    volumes:
      - ./extras/data/postress_data:/var/lib/postgresql/data
    networks: 
      - PP2_network 
    ports:
      - '5432:5432'
  practicepractice:
    build: .
    depends_on: 
      - PP2DB
    container_name: container_pp2
    networks: 
      - PP2_network 
    ports:
      - '8005:80'

networks:
  PP2_network:
