apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::601197766298:role/eksctl-eks-practicepractice-nodeg-NodeInstanceRole-QFTEYDCEMQQT
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::601197766298:user/eks-practicepractice
      username: eks-practicepractice
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-17T10:54:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1183"
  uid: ee9ed1a3-b05f-482e-ad0c-159150252ec7
