apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::601197766298:role/eksctl-eks-practicepractice-nodeg-NodeInstanceRole-1G7TMUMMGHR1B
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::601197766298:user/eks-practicepractice
      username: eks-practicepractice
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-14T08:59:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1217"
  uid: afa31717-0aa5-4aeb-b65b-806b6ab7d6f5
