apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::601197766298:role/eksctl-eks-practicepractice-nodeg-NodeInstanceRole-1SDMWDQ3XBYD0
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::601197766298:user/eks-practicepractice
      username: eks-practicepractice
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-07T12:10:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1280"
  uid: a29e7054-2b79-45c9-8af3-a5d65be2bd85
