apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::601197766298:role/eksctl-eks-practicepractice-nodeg-NodeInstanceRole-106RNYP466UTT
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::601197766298:user/eks-practicepractice
      username: eks-practicepractice
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-05T15:47:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1141"
  uid: b28d65bf-f3e6-4793-ae80-e7c5720876df
