apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::601197766298:role/eksctl-eks-practicepractice-nodeg-NodeInstanceRole-15IS2F76ACCHC
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
      - userarn: arn:aws:iam::601197766298:user/eks-practicepractice
        username: eks-practicepractice
        groups:
          - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-06T20:30:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1260"
  uid: e7afe868-eb30-4d84-905a-8151a08835c0
