# Generated by Django 4.0.1 on 2022-11-15 14:38

import collections
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('content', models.JSONField(default=collections.OrderedDict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=150, null=True)),
                ('course_publication', models.BooleanField(default=False, null=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw_subject', models.CharField(db_index=True, default='', max_length=50, null=True)),
                ('kw_word', models.CharField(default='', max_length=50, null=True)),
                ('kw_multiple_context', models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_level', models.CharField(default='', max_length=50, null=True)),
                ('p_subject', models.CharField(default='', max_length=255, null=True)),
                ('p_moduel', models.CharField(default='', max_length=255, null=True)),
                ('p_chapter', models.CharField(default='', max_length=255, null=True)),
                ('p_topic', models.CharField(default='', max_length=255, null=True)),
                ('p_number', models.IntegerField(default=-1, null=True)),
                ('p_content', models.JSONField(default=dict, null=True)),
                ('p_directory', models.CharField(default='', max_length=255, null=True)),
                ('p_link', models.CharField(default='', max_length=256, null=True)),
                ('p_unique_id', models.CharField(db_index=True, default='', max_length=11, null=True, unique=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_level', models.CharField(default='', max_length=30, null=True)),
                ('q_board', models.CharField(default='', max_length=10, null=True)),
                ('q_board_moduel', models.CharField(default='', max_length=50, null=True)),
                ('q_exam_month', models.IntegerField(default=0, null=True)),
                ('q_exam_year', models.IntegerField(default=0, null=True)),
                ('q_is_exam', models.BooleanField(default=False, null=True)),
                ('q_exam_num', models.IntegerField(default=0, null=True)),
                ('q_subject', models.CharField(default='', max_length=50, null=True)),
                ('q_moduel', models.CharField(default='', max_length=50, null=True)),
                ('q_chapter', models.CharField(default='', max_length=50, null=True)),
                ('q_topic', models.CharField(default='', max_length=50, null=True)),
                ('q_type', models.CharField(default='', max_length=50, null=True)),
                ('q_difficulty', models.IntegerField(default=0, null=True)),
                ('q_total_marks', models.IntegerField(default=0, null=True)),
                ('q_content', models.JSONField(default=dict, null=True)),
                ('q_dir', models.CharField(default='', max_length=255, null=True)),
                ('q_link', models.CharField(default='', max_length=255, null=True)),
                ('q_unique_id', models.CharField(db_index=True, default='', max_length=11, null=True, unique=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_unique_id', models.CharField(db_index=True, default='', max_length=11, null=True)),
                ('v_title', models.CharField(default='', max_length=255)),
                ('v_link', models.CharField(default='', max_length=255)),
                ('v_pos', models.IntegerField(default=0, null=True)),
                ('v_health', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pap_subject', models.CharField(default='', max_length=50)),
                ('pap_info', models.JSONField(default=dict, null=True)),
                ('pap_creation_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_level', models.CharField(default='', max_length=50, null=True)),
                ('spec_subject', models.CharField(default='', max_length=50, null=True)),
                ('spec_board', models.CharField(default='', max_length=50, null=True)),
                ('spec_name', models.CharField(default='', max_length=50, null=True)),
                ('spec_first_assessment', models.DateTimeField(blank=True, null=True, verbose_name='First assessment')),
                ('spec_last_assessment', models.DateTimeField(blank=True, null=True, verbose_name='Last assessment')),
                ('spec_content', models.JSONField(default=collections.OrderedDict, null=True)),
                ('spec_completion', models.BooleanField(default=False, null=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_mark', models.IntegerField(default=0, null=True)),
                ('track_creation_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('question', models.ForeignKey(db_column='q_unique_id', on_delete=django.db.models.deletion.CASCADE, to='content.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_subject', models.CharField(default='', max_length=255, null=True)),
                ('task_moduel', models.CharField(default='', max_length=255, null=True)),
                ('task_chapter', models.CharField(default='', max_length=255, null=True)),
                ('task_topic', models.CharField(default='', max_length=255, null=True)),
                ('task_payment_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('task_completion_status', models.BooleanField(default=False, null=True)),
                ('task_approval_status', models.BooleanField(default=False, null=True)),
                ('task_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='specification',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.specification'),
        ),
    ]
