# Generated by Django 4.0.1 on 2022-11-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='spec_level',
        ),
        migrations.AddField(
            model_name='specification',
            name='spec_leve',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
