# Generated by Django 4.0.1 on 2022-11-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttemplate',
            name='content',
            field=models.JSONField(null=True),
        ),
    ]
