# Generated by Django 4.0.1 on 2022-11-19 16:13

import collections
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contenttemplate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttemplate',
            name='content',
            field=models.JSONField(default=collections.OrderedDict, null=True),
        ),
    ]
