# Generated by Django 4.0.1 on 2022-03-20 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_points_point_rename_questions_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='p_related_questions',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='content.question'),
            preserve_default=False,
        ),
    ]
