# Generated by Django 4.0.1 on 2022-12-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_question_q_mdcontent'),
    ]
