# Generated by Django 4.0.1 on 2023-01-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_point_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='is_completed',
            new_name='is_completed_content',
        ),
        migrations.AddField(
            model_name='point',
            name='is_completed_questions',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
