# Generated by Django 4.0.1 on 2022-09-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='v_health',
            field=models.BooleanField(null=True),
        ),
    ]
