# Generated by Django 4.0.1 on 2022-11-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_specification_spec_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='spec_leve',
        ),
    ]
