# Generated by Django 4.0.1 on 2023-01-16 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_rename_is_completed_point_is_completed_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator_type', models.CharField(choices=[(1, 'Freelancer'), (2, 'Partner'), (3, 'Volenteer')], default=None, max_length=1)),
                ('rate_per_point', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate_per_question', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentage_split', models.IntegerField(default=-1, null=True)),
                ('specification', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.specification')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
