# Generated by Django 4.0.1 on 2022-03-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_point_p_related_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='p_related_questions',
        ),
    ]
