# Generated by Django 4.0.1 on 2022-12-08 12:44

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_question_q_mdcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_MDcontent',
            field=mdeditor.fields.MDTextField(default='', null=True),
        ),
    ]
