# Generated by Django 4.0.1 on 2023-01-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='collaborator_type',
            field=models.CharField(choices=[(1, 'Freelancer'), (2, 'Partner'), (3, 'Volenteer')], default='Volenteer', max_length=1),
        ),
    ]
