# Generated by Django 4.0.1 on 2022-09-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_examplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_board_moduel',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
