# Generated by Django 4.0.1 on 2022-11-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_specification_spec_leve'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='spec_in_house',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
