# Generated by Django 4.0.1 on 2022-12-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_point_p_mdcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontrack',
            name='track_attempt_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
