# Generated by Django 4.0.1 on 2022-11-29 19:25

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
