# Generated by Django 4.0.1 on 2023-01-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_collaborator_collaborator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='condition_acceptance',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='initial_invite_acceptance',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
