# Generated by Django 4.0.1 on 2022-03-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
