# Generated by Django 4.0.1 on 2022-04-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_chapter',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='q_difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='q_dir',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='q_exam_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='q_is_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='q_level',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='q_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='q_moduel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='q_origin',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='q_topic',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='q_total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='q_type',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='q_unique_id',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_subject',
            field=models.CharField(default='', max_length=50),
        ),
    ]
