# Generated by Django 4.0.1 on 2022-10-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_point_p_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='q_exam_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='specification',
            name='spec_health',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
