# Generated by Django 4.0.1 on 2022-12-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_questiontrack_track_attempt_number'),
    ]

