# Generated by Django 4.0.1 on 2022-11-29 19:45

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_examplemodel_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='p_MDcontent',
            field=mdeditor.fields.MDTextField(default=5),
            preserve_default=False,
        ),
    ]
