# Generated by Django 4.0.1 on 2022-11-29 20:09

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_point_p_mdcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='p_MDcontent',
            field=mdeditor.fields.MDTextField(default='', null=True),
        ),
    ]
