# Generated by Django 4.0.1 on 2022-10-18 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0007_specification_q_exam_num_specification_spec_health'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.specification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
