# Generated by Django 4.0.1 on 2022-11-17 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0007_alter_point_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='p_link',
        ),
        migrations.AddField(
            model_name='point',
            name='p_in_house',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='p_in_house',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
