# Generated by Django 4.0.1 on 2022-12-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_questiontrack_track_attempt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontrack',
            name='track_attempt_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
