# Generated by Django 4.0.1 on 2022-11-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_courseversion_version_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_content',
        ),
    ]
