# Generated by Django 4.0.1 on 2023-01-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_collaborator_orchistrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='rate_per_point',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='rate_per_question',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
