# Generated by Django 4.0.1 on 2022-12-12 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_questiontrack_track_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontrack',
            name='course',
            field=models.ForeignKey(db_column='realted_course', default=0, on_delete=django.db.models.deletion.CASCADE, to='content.course'),
            preserve_default=False,
        ),
    ]
