# Generated by Django 4.0.1 on 2022-11-29 22:27

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_point_p_mdcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttemplate',
            name='MDcontent',
            field=mdeditor.fields.MDTextField(default='', null=True),
        ),
    ]
