# Generated by Django 4.0.1 on 2022-11-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_course_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_summary',
            field=models.TextField(default='', max_length=255, null=True),
        ),
    ]
