# Generated by Django 4.0.1 on 2022-04-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_question_q_chapter_alter_question_q_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_type',
        ),
        migrations.AlterField(
            model_name='question',
            name='q_unique_id',
            field=models.CharField(db_index=True, default='', max_length=11, null=True, unique=True),
        ),
    ]
