# Generated by Django 4.0.1 on 2023-01-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_collaborator_rate_per_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
