# Generated by Django 4.0.1 on 2022-10-19 07:16

import collections
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_rename_specificationsubscriptions_specificationsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='spec_content',
            field=models.JSONField(default=collections.OrderedDict, null=True),
        ),
    ]
