# Generated by Django 4.0.1 on 2022-04-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_question_q_type_alter_question_q_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_type',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
