# Generated by Django 4.0.1 on 2022-12-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_questiontrack_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontrack',
            name='course',
            field=models.ForeignKey(db_column='specification', on_delete=django.db.models.deletion.CASCADE, to='content.course'),
        ),
    ]
