# Generated by Django 4.0.1 on 2022-12-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_contenttemplate_mdcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='p_directory',
            new_name='p_files_directory',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='q_dir',
            new_name='q_files_directory',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_link',
        ),
    ]
