# Generated by Django 4.0.1 on 2023-01-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_collaborator_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='specification',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='specification',
            field=models.ManyToManyField(db_index=True, default='', null=True, to='content.Specification'),
        ),
    ]
