# Generated by Django 4.0.1 on 2022-11-22 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_course_course_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_summary',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
    ]
