# Generated by Django 4.0.1 on 2022-10-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_specification_spec_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='spec_publication',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
