# Generated by Django 4.0.1 on 2022-11-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaper',
            name='pap_subject',
        ),
        migrations.AddField(
            model_name='userpaper',
            name='pap_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.course'),
        ),
    ]
