# Generated by Django 4.0.1 on 2022-12-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_rename_p_directory_point_p_files_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_question_bank_only',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
