# Generated by Django 4.0.1 on 2022-12-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_questiontrack_track_mark_boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaper',
            name='pap_completion',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
