# Generated by Django 4.0.1 on 2022-12-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_course_course_question_bank_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_picture_upload',
            field=models.FileField(blank=True, upload_to='uploads/course_picture'),
        ),
    ]
