# Generated by Django 4.0.1 on 2022-11-25 11:35

import collections
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0011_courseversion_version_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_contributors',
            field=models.JSONField(default=collections.OrderedDict, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_estimated_time',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_language',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_learning_objectives',
            field=models.JSONField(default=collections.OrderedDict, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_skills',
            field=models.JSONField(default=collections.OrderedDict, null=True),
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_stars', models.PositiveSmallIntegerField(null=True)),
                ('review_text', models.CharField(default='', max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
