# Generated by Django 4.0.1 on 2022-11-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_userpaper_pap_subject_userpaper_pap_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editingtask',
            name='task_subject',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='kw_multiple_context',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='kw_subject',
        ),
        migrations.AddField(
            model_name='editingtask',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.specification'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='kw_definition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.specification'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='kw_word',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
