# Generated by Django 4.0.1 on 2022-11-17 09:43

import collections
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_remove_editingtask_task_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_content',
            field=models.JSONField(default=collections.OrderedDict, null=True),
        ),
    ]
