# Generated by Django 4.0.1 on 2022-04-06 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_question_q_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_exam_number',
        ),
    ]
