# Generated by Django 4.0.1 on 2023-01-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_remove_collaborator_specifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='specifications',
            new_name='specification',
        ),
    ]
