# Generated by Django 4.0.1 on 2022-12-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_course_course_picture_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_pic_status',
            field=models.BooleanField(default=False),
        ),
    ]
