# Generated by Django 4.0.1 on 2022-11-27 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_coursereview_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubscription',
            name='subscription_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
