# Generated by Django 4.0.1 on 2022-12-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_course_course_pic_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_picture_upload',
        ),
    ]
