# Generated by Django 4.0.1 on 2023-01-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_rename_specifications_collaborator_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubscription',
            name='archived',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='owned',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='subscription_ended_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
