# Generated by Django 4.0.1 on 2022-04-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_remove_question_q_exam_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_exam_month',
            field=models.IntegerField(default='', null=True),
        ),
    ]
