# Generated by Django 4.0.1 on 2022-04-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_question_q_exam_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_content',
            field=models.JSONField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_exam_month',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
