# Generated by Django 4.0.1 on 2023-01-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_coursesubscription_archived_coursesubscription_owned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubscription',
            name='subscription_ended_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
