# Generated by Django 4.0.1 on 2022-12-04 17:16

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_course_course_pic_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_MDcontent',
            field=mdeditor.fields.MDTextField(default='', null=True),
        ),
    ]
