# Generated by Django 4.0.1 on 2023-01-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_coursesubscription_subscription_ended_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesubscription',
            name='archived',
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='visibility',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
