# Generated by Django 4.0.1 on 2023-01-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_remove_coursesubscription_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='condition_created',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
