# Generated by Django 4.0.1 on 2023-01-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_collaborator_condition_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='collaborator_type',
            field=models.CharField(choices=[('1', 'Freelancer'), ('2', 'Partner'), ('3', 'Volenteer')], default='Volenteer', max_length=1),
        ),
    ]
