# Generated by Django 4.0.1 on 2022-04-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_point_p_directory_alter_point_p_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='p_directory',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='p_link',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
