# Generated by Django 4.0.1 on 2023-01-31 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_collaborator_collaborator_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.JSONField(default=dict, null=True)),
                ('active', models.BooleanField(default=False, null=True)),
                ('collaboration', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaboration', to='content.collaborator')),
            ],
        ),
    ]
