# Generated by Django 4.0.1 on 2023-02-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_remove_contract_active_contract_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='collaboration',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='collaboration', to='content.collaborator'),
        ),
    ]
