# Generated by Django 4.0.1 on 2023-02-26 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_alter_contract_collaboration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator_type', models.CharField(choices=[('1', 'Notes'), ('2', 'Question')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted', models.BooleanField(default=False, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('collaboration', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_contribution', to='content.collaborator')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='collaboration',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_contract', to='content.collaborator'),
        ),
        migrations.DeleteModel(
            name='EditingTask',
        ),
    ]
