# Generated by Django 4.0.1 on 2022-04-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_alter_point_p_chapter_alter_point_p_moduel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='p_unique_id',
            field=models.CharField(db_index=True, default='', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='v_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='v_pos',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='v_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
