# Generated by Django 4.0.1 on 2022-04-06 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0022_video_p_unique_id_video_v_link_video_v_pos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pap_subject', models.JSONField(default=dict, null=True)),
                ('pap_info', models.JSONField(default=dict, null=True)),
                ('pap_creation_time', models.JSONField(default=dict, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
