# Generated by Django 4.0.1 on 2023-02-27 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_contribution_alter_contract_collaboration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='collaboration',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='collaborator_type',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='submitted',
        ),
        migrations.AddField(
            model_name='contribution',
            name='new_content',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='point',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution_point', to='content.point'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='question',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution_question', to='content.question'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ContributionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_moduel', models.CharField(default='', max_length=255, null=True)),
                ('task_chapter', models.CharField(default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted', models.BooleanField(default=False, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('collaboration', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_contribution', to='content.collaborator')),
            ],
        ),
        migrations.AddField(
            model_name='contribution',
            name='task',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_contribution', to='content.contributiontask'),
        ),
    ]
