# Generated by Django 4.0.1 on 2022-04-06 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0023_userpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaper',
            name='pap_creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='userpaper',
            name='pap_subject',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='QuestionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_mark', models.IntegerField(default=0, null=True)),
                ('track_creation_time', models.DateTimeField(verbose_name='date created')),
                ('question', models.ForeignKey(db_column='q_unique_id', on_delete=django.db.models.deletion.CASCADE, to='content.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
