# Generated by Django 4.0.1 on 2023-03-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_remove_contribution_collaboration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontask',
            name='ended',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
