# Generated by Django 4.0.1 on 2023-03-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_contributiontask_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='is_point',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='is_question',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
