# Generated by Django 4.0.1 on 2022-04-06 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_alter_userpaper_pap_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontrack',
            name='track_creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
