# Generated by Django 4.0.1 on 2022-04-06 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_alter_questiontrack_track_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaper',
            name='pap_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 12, 55, 22, 187923, tzinfo=utc), verbose_name='date created'),
        ),
    ]
