# Generated by Django 4.0.1 on 2023-04-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_contribution_is_point_contribution_is_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='erased',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='erased',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
