# Generated by Django 4.0.1 on 2022-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_alter_userpaper_pap_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontrack',
            name='track_creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='userpaper',
            name='pap_creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
