# Generated by Django 4.0.1 on 2022-04-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_alter_questiontrack_track_creation_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw_subject', models.CharField(db_index=True, default='', max_length=50, null=True)),
                ('kw_word', models.CharField(default='', max_length=50, null=True)),
                ('kw_multiple_context', models.JSONField(default=dict, null=True)),
            ],
        ),
    ]
