# Generated by Django 4.0.1 on 2023-04-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_remove_question_q_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_answer',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
