# Generated by Django 4.0.1 on 2022-04-06 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0029_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editing_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_subject', models.CharField(default='', max_length=255, null=True)),
                ('task_moduel', models.CharField(default='', max_length=255, null=True)),
                ('task_chapter', models.CharField(default='', max_length=255, null=True)),
                ('task_topic', models.CharField(default='', max_length=255, null=True)),
                ('task_payment_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('task_completion_status', models.BooleanField(default=False, null=True)),
                ('task_approval_status', models.BooleanField(default=False, null=True)),
                ('task_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
