# Generated by Django 4.0.1 on 2023-05-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_question_q_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_question_bank_only',
        ),
    ]
