# Generated by Django 4.0.1 on 2023-05-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_remove_course_course_question_bank_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='spec_completion',
        ),
    ]
