# Generated by Django 4.0.1 on 2022-04-06 14:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0030_editing_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editing_task',
            new_name='EditingTask',
        ),
    ]
