# Generated by Django 4.0.1 on 2022-04-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_rename_editing_task_editingtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_board', models.CharField(default='', max_length=50, null=True)),
                ('spec_subject', models.CharField(default='', max_length=50, null=True)),
                ('spec_name', models.CharField(default='', max_length=50, null=True)),
                ('spec_first_assessment', models.DateTimeField(blank=True, verbose_name='First assessment')),
                ('spec_last_assessment', models.DateTimeField(blank=True, verbose_name='Last assessment')),
                ('spec_content', models.JSONField(default=dict, null=True)),
            ],
        ),
    ]
