# Generated by Django 4.0.1 on 2023-05-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_remove_specification_spec_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_language',
        ),
    ]
