# Generated by Django 4.0.1 on 2022-04-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='p_level',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='q_level',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
