# Generated by Django 4.0.1 on 2023-05-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_remove_course_course_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_estimated_time',
        ),
    ]
