# Generated by Django 4.0.1 on 2022-04-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_point_p_level_question_q_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='spec_level',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
