# Generated by Django 4.0.1 on 2023-05-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_rename_review_created_at_coursereview_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereview',
            old_name='created_at',
            new_name='review_created_at',
        ),
        migrations.RemoveField(
            model_name='coursesubscription',
            name='reviewed',
        ),
    ]
