# Generated by Django 4.0.1 on 2022-04-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_specification_spec_dir_specification_spec_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='spec_first_assessment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First assessment'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='spec_last_assessment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last assessment'),
        ),
    ]
