# Generated by Django 4.0.1 on 2023-05-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_point_p_images_point_p_videos_question_q_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
