# Generated by Django 4.0.1 on 2023-05-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_alter_image_url_alter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
