# Generated by Django 4.0.1 on 2023-05-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='p_title',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
