# Generated by Django 4.0.1 on 2023-05-20 08:58

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_point_p_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_MDcontent_ans',
            field=mdeditor.fields.MDTextField(default='', null=True),
        ),
    ]
