# Generated by Django 4.0.1 on 2023-05-20 08:58
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_point_p_title'),
    ]

    operations = [
    ]
