# Generated by Django 4.0.1 on 2023-05-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_question_q_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='placement',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
