# Generated by Django 4.0.1 on 2023-07-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_remove_video_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontrack',
            name='theme',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Ok'), ('3', 'Hard')], max_length=3, null=True),
        ),
    ]
