# Generated by Django 4.0.1 on 2023-07-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_remove_questiontrack_theme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontrack',
            name='track_mark_boolean',
        ),
    ]
