# Generated by Django 4.0.1 on 2023-07-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_alter_questiontrack_track_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_marks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='questiontrack',
            name='precieved_difficulty',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Ok'), ('3', 'Hard')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='questiontrack',
            name='total_marks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questiontrack',
            name='track_mark',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
