# Generated by Django 4.0.1 on 2023-07-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0053_question_q_marks_questiontrack_precieved_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_marks',
            field=models.IntegerField(default=1),
        ),
    ]
