# Generated by Django 4.0.1 on 2023-08-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0054_alter_question_q_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaper',
            name='pap_q_marks',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
