# Generated by Django 4.0.1 on 2023-08-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0055_userpaper_pap_q_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaper',
            name='percentage_score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
