# Generated by Django 4.0.1 on 2023-08-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0058_remove_course_course_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='collaboration',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='point',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='question',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='task',
        ),
        migrations.RemoveField(
            model_name='contributiontask',
            name='collaboration',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='specification',
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='ContributionTask',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
