# Generated by Django 4.0.1 on 2023-08-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0059_remove_contract_collaboration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_up_to_date',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
