# Generated by Django 4.0.1 on 2023-08-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0060_course_course_up_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='author_confirmation',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='author_confirmation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
