# Generated by Django 4.0.1 on 2023-08-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0061_point_author_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubscription',
            name='progress_track',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
