# Generated by Django 4.0.1 on 2023-09-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0062_coursesubscription_progress_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='generated_content',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='generated_outline',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='generated_questions',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='generated_summary',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
