# Generated by Django 4.0.1 on 2023-09-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0064_course_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(default='', max_length=5000, null=True),
        ),
    ]
