# Generated by Django 4.0.1 on 2023-09-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0065_alter_course_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
