# Generated by Django 4.0.1 on 2023-09-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0066_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='specification',
            field=models.ForeignKey(default='Specialisation', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.specification'),
        ),
    ]
