version: "3.3"
services: 
  PP2DB:
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123
    volumes:
      - ./extras/data/postgres/:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'
    networks: 
      - PP2_network 
networks:
  PP2_network:
