version: "3.3"
services: 
  PP2DB:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: django_db_user
      POSTGRES_PASSWORD: Password123
    volumes:
      - ./extras/data/postress_data:/var/lib/postgresql/data
    networks: 
      - PP2_network 

  practicepractice:
    build: .
    depends_on: 
      - PP2DB
    container_name: container_pp2
    networks: 
      - PP2_network 
    volumes:
      - ./extras/data/content/:/pp2/content/
    ports:
      - '8005:80'
    extra_hosts:
        - "practicepractice.net:54.78.240.123" #host and ip
        - "www.practicepractice.net:54.78.240.123" #host and ip

networks:
  PP2_network:
