# Generated by Django 4.0.1 on 2022-04-07 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_transfer_arrow', models.BooleanField(default=False, null=True)),
                ('payment_id', models.CharField(default='', max_length=255, null=True)),
                ('payment_hash', models.CharField(default='', max_length=255, null=True)),
                ('payment_status', models.BooleanField(default=False, null=True)),
                ('payment_completion_time', models.DateTimeField(blank=True, verbose_name='date created')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
