# Generated by Django 4.0.1 on 2023-04-07 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0025_contribution_is_point_contribution_is_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduel', models.CharField(default='', max_length=50, null=True)),
                ('conditions', models.JSONField(default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terminated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_lesson_course', to='content.course')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_lesson_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
