# Generated by Django 4.0.1 on 2023-04-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0002_rename_conditions_lesson_lesson_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='moduel',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
