# Generated by Django 4.0.1 on 2023-04-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0004_lesson_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_pointer',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
