# Generated by Django 4.0.1 on 2023-04-09 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AI', '0005_lesson_lesson_pointer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_chat',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_pointer',
        ),
        migrations.CreateModel(
            name='Lesson_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(default='', max_length=150, null=True)),
                ('lesson_chat', models.JSONField(default=dict, null=True)),
                ('lesson_content', models.JSONField(default=dict, null=True)),
                ('lesson_pointer', models.CharField(default='', max_length=250, null=True)),
                ('lesson_token_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terminated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('lesson', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_lesson_course', to='AI.lesson')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_lesson_part_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
