# Generated by Django 4.0.1 on 2023-04-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0006_remove_lesson_lesson_chat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson_part',
            old_name='lesson_chat',
            new_name='part_chat',
        ),
        migrations.RenameField(
            model_name='lesson_part',
            old_name='lesson_content',
            new_name='part_content',
        ),
        migrations.RenameField(
            model_name='lesson_part',
            old_name='lesson_pointer',
            new_name='part_pointer',
        ),
        migrations.RenameField(
            model_name='lesson_part',
            old_name='lesson_token_count',
            new_name='part_token_count',
        ),
    ]
