# Generated by Django 4.0.1 on 2023-04-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0007_rename_lesson_chat_lesson_part_part_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_part',
            name='part_introduction',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
