# Generated by Django 4.0.1 on 2023-04-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0008_lesson_part_part_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_part',
            name='part_introduction',
            field=models.TextField(default='', null=True),
        ),
    ]
