# Generated by Django 4.0.1 on 2023-04-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0009_alter_lesson_part_part_introduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson_part',
            old_name='chapter',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
