# Generated by Django 4.0.1 on 2023-05-07 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0036_rename_created_at_coursereview_review_created_at_and_more'),
        ('AI', '0012_contentprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPromptPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduel', models.CharField(default='', max_length=255, null=True)),
                ('chapter', models.CharField(default='', max_length=255, null=True)),
                ('topic', models.CharField(default='', max_length=255, null=True)),
                ('point_number', models.IntegerField(default=-1, null=True)),
                ('prompt', models.TextField(default='', max_length=2500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False, null=True)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_contentprompt_course_point', to='content.course')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_contentprompt_user_point', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentPromptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduel', models.CharField(default='', max_length=255, null=True)),
                ('chapter', models.CharField(default='', max_length=255, null=True)),
                ('topic', models.CharField(default='', max_length=255, null=True)),
                ('level', models.IntegerField(default=-1, null=True)),
                ('prompt', models.TextField(default='', max_length=2500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False, null=True)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_contentprompt_course_question', to='content.course')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_contentprompt_user_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentPromptTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduel', models.CharField(default='', max_length=255, null=True)),
                ('chapter', models.CharField(default='', max_length=255, null=True)),
                ('topic', models.CharField(default='', max_length=255, null=True)),
                ('prompt', models.TextField(default='', max_length=2500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False, null=True)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_contentprompt_course_topic', to='content.course')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_contentprompt_user_topic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ContentPrompt',
        ),
    ]
