# Generated by Django 4.0.1 on 2023-05-08 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_rename_created_at_coursereview_review_created_at_and_more'),
        ('AI', '0013_contentpromptpoint_contentpromptquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpromptpoint',
            name='course',
        ),
        migrations.RemoveField(
            model_name='contentpromptquestion',
            name='course',
        ),
        migrations.RemoveField(
            model_name='contentprompttopic',
            name='course',
        ),
        migrations.AddField(
            model_name='contentpromptpoint',
            name='specification',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_contentprompt_specification_point', to='content.specification'),
        ),
        migrations.AddField(
            model_name='contentpromptquestion',
            name='specification',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_contentprompt_specification_question', to='content.specification'),
        ),
        migrations.AddField(
            model_name='contentprompttopic',
            name='specification',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_contentprompt_specification_topic', to='content.specification'),
        ),
    ]
