# Generated by Django 4.0.1 on 2023-05-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0014_remove_contentpromptpoint_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpromptquestion',
            name='topic',
        ),
    ]
