# Generated by Django 4.0.1 on 2023-05-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0015_remove_contentpromptquestion_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpromptpoint',
            name='point_number',
        ),
        migrations.AddField(
            model_name='contentpromptpoint',
            name='p_unique',
            field=models.CharField(default='', max_length=11, null=True),
        ),
    ]
