# Generated by Django 4.0.1 on 2023-05-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0017_contentgenerationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgenerationjob',
            name='finished',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='contentgenerationjob',
            name='started',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
