# Generated by Django 4.0.1 on 2023-05-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0018_contentgenerationjob_finished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentprompttopic',
            name='activated',
        ),
    ]
