# Generated by Django 4.0.1 on 2023-05-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0019_remove_contentprompttopic_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentgenerationjob',
            name='started',
        ),
    ]
