# Generated by Django 4.0.1 on 2023-05-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0021_remove_lesson_part_part_introduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_content',
        ),
    ]
