# Generated by Django 4.0.1 on 2023-06-16 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0022_remove_lesson_lesson_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_introduction',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='terminated_at',
        ),
        migrations.RemoveField(
            model_name='lesson_part',
            name='part_content',
        ),
    ]
