# Generated by Django 4.0.1 on 2023-06-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0023_remove_lesson_lesson_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_part',
            name='part_content',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
