# Generated by Django 4.0.1 on 2023-07-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0024_lesson_part_part_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_part',
            name='part_token_count',
        ),
        migrations.AddField(
            model_name='lesson_part',
            name='completion',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='lesson_part',
            name='prompt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='lesson_part',
            name='recording_switch',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='lesson_part',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
