# Generated by Django 4.0.1 on 2023-07-14 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AI', '0025_remove_lesson_part_part_token_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.IntegerField(default=0, null=True)),
                ('AI_quiz', models.JSONField(default=dict, null=True)),
                ('prompt', models.IntegerField(default=0, null=True)),
                ('completion', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('recording_switch', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_part', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_lesson_part', to='AI.lesson')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_lesson_quiz_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
