# Generated by Django 4.0.1 on 2023-07-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0026_lesson_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_quiz',
            name='AI_quiz',
        ),
        migrations.RemoveField(
            model_name='lesson_quiz',
            name='completion',
        ),
        migrations.RemoveField(
            model_name='lesson_quiz',
            name='point_id',
        ),
        migrations.RemoveField(
            model_name='lesson_quiz',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='lesson_quiz',
            name='recording_switch',
        ),
        migrations.RemoveField(
            model_name='lesson_quiz',
            name='total',
        ),
        migrations.AddField(
            model_name='lesson_quiz',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='lesson_quiz',
            name='quiz',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='lesson_quiz',
            name='quiz_id',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='lesson_quiz',
            name='user_answers',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
