# Generated by Django 4.0.1 on 2023-07-22 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0027_remove_lesson_quiz_ai_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_quiz',
            name='lesson_part',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AI_lesson_part', to='AI.lesson_part'),
        ),
    ]
