# Generated by Django 4.0.1 on 2023-08-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0028_alter_lesson_quiz_lesson_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_part',
            name='part_chat',
            field=models.JSONField(default=dict),
        ),
    ]
