# Generated by Django 4.0.1 on 2023-08-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0031_alter_lesson_quiz_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_quiz',
            name='percentage_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
