# Generated by Django 4.0.1 on 2023-08-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0032_lesson_quiz_percentage_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_quiz',
            name='percentage_score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
