# Generated by Django 4.0.1 on 2023-09-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0033_alter_lesson_quiz_percentage_score'),
    ]

    operations = [
    ]
