# Generated by Django 4.0.1 on 2023-09-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0034_contentgenerationjob_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentgenerationjob',
            name='test',
        ),
        migrations.RemoveField(
            model_name='lesson_part',
            name='recording_switch',
        ),
    ]
