# Generated by Django 4.0.1 on 2023-04-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('lig', 'Light'), ('dar', 'Dark'), ('lib', 'Library')], default='dar', max_length=3),
        ),
    ]
