# Generated by Django 4.0.1 on 2022-09-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='roles',
            field=models.CharField(choices=[('General', 'Fully Privileged Administrator'), ('Subject', 'Subject Specific Adminstrator')], max_length=10, null=True),
        ),
    ]
