# Generated by Django 4.0.1 on 2022-08-28 14:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_mail_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Date_of_brith',
            new_name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='user',
            name='mail_choices',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GroupChange', 'GroupChange'), ('ProductUpdate', 'ProductUpdate'), ('New', 'New'), ('Marketing', 'Marketing'), ('Core', 'Core')], default=['GroupChange', 'ProductUpdate', 'New', 'Marketing', 'Core'], max_length=90),
        ),
    ]
