# Generated by Django 4.0.1 on 2022-11-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
