# Generated by Django 4.0.1 on 2023-04-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('lig', 'Light'), ('dar', 'Dark')], default='dar', max_length=3),
        ),
    ]
