# Generated by Django 4.0.1 on 2022-09-04 11:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_admin_approval_status_admin_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], default=[], max_length=84),
        ),
    ]
