# Generated by Django 4.0.1 on 2022-05-21 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_rename_affiliate_affiliatebalance_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userappinformation',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userappinformation',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userappinformation',
            name='location',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
