# Generated by Django 4.0.1 on 2022-08-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
