# Generated by Django 4.0.1 on 2022-11-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_verification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_status',
        ),
    ]
