# Generated by Django 4.0.1 on 2023-08-20 19:36

import collections
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_significant_clicks',
            field=models.JSONField(default=collections.OrderedDict, null=True),
        ),
    ]
