# Generated by Django 4.0.1 on 2022-11-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_details_complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
