# Generated by Django 4.0.1 on 2022-05-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userappinformation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAppInformation',
        ),
    ]
