# Generated by Django 4.0.1 on 2022-08-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_mobile_number_user_bio_user_is_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_date',
            new_name='Date_of_brith',
        ),
    ]
