# Generated by Django 4.0.1 on 2023-08-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_monthly_significant_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliate_permissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='author_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
