# Generated by Django 4.0.1 on 2022-11-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_account_details_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_details_complete',
            field=models.BooleanField(default=False),
        ),
    ]
