# Generated by Django 4.0.1 on 2023-09-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_affiliate_permissions_user_author_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliate_promotion_code',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
