# Generated by Django 4.0.1 on 2022-05-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_userappinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration',
            field=models.BooleanField(null=True),
        ),
    ]
