# Generated by Django 4.0.1 on 2022-08-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_billing_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
