# Generated by Django 4.0.1 on 2022-08-29 13:58

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('user', '0006_user_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address'),
        ),
        migrations.AddField(
            model_name='school',
            name='Icon_id',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='Incorpiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='N_classes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='N_managers',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='N_students',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='N_teachers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='phone_number',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tuitioncenter',
            name='Address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address'),
        ),
        migrations.AddField(
            model_name='tuitioncenter',
            name='Icon_id',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tuitioncenter',
            name='Incorpiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tuitioncenter',
            name='N_classes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tuitioncenter',
            name='N_managers',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='tuitioncenter',
            name='N_students',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tuitioncenter',
            name='N_teachers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tuitioncenter',
            name='URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tuitioncenter',
            name='name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tuitioncenter',
            name='phone_number',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Icon_id',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
