# Generated by Django 4.0.1 on 2022-09-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_student_educator_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='educator_affiliation',
            field=models.ManyToManyField(blank=True, related_name='student_edu_affiliation', to='user.Educator'),
        ),
        migrations.AlterField(
            model_name='student',
            name='organisation_affiliation',
            field=models.ManyToManyField(blank=True, related_name='student_org_affiliation', to='user.Organisation'),
        ),
    ]
