# Generated by Django 4.0.1 on 2022-05-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registration',
            field=models.BooleanField(default=False),
        ),
    ]
