# Generated by Django 4.0.1 on 2022-05-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userprofile_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='registration',
            new_name='registered_status',
        ),
    ]
