# Generated by Django 4.0.1 on 2022-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_account_details_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_details_complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
