# Generated by Django 4.0.1 on 2022-08-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_school_address_school_icon_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitioncenter',
            name='Icon_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
