# Generated by Django 4.0.1 on 2022-09-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_student_educator_affiliation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subjects',
            new_name='studied_subjects',
        ),
    ]
