# Generated by Django 4.0.1 on 2022-08-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_tuitioncenter_icon_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='Icon_id',
            new_name='icon_id',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='Incorpiration_date',
            new_name='incorpiration_date',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='N_classes',
            new_name='n_classes',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='N_managers',
            new_name='n_managers',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='N_students',
            new_name='n_students',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='N_teachers',
            new_name='n_teachers',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='URL',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='tuitioncenter',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='tuitioncenter',
            old_name='Incorpiration_date',
            new_name='incorpiration_date',
        ),
        migrations.RenameField(
            model_name='tuitioncenter',
            old_name='N_classes',
            new_name='n_classes',
        ),
        migrations.RenameField(
            model_name='tuitioncenter',
            old_name='N_managers',
            new_name='n_managers',
        ),
        migrations.RenameField(
            model_name='tuitioncenter',
            old_name='N_students',
            new_name='n_students',
        ),
        migrations.RenameField(
            model_name='tuitioncenter',
            old_name='N_teachers',
            new_name='n_teachers',
        ),
        migrations.RenameField(
            model_name='tuitioncenter',
            old_name='URL',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='tuitioncenter',
            name='Icon_id',
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tuitioncenter',
            name='icon_id',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tuitioncenter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
