# Generated by Django 4.0.1 on 2022-11-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_group_details_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group_details_complete',
        ),
    ]
