# Generated by Django 4.0.1 on 2022-08-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_address_school_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='incorpiration_date',
            new_name='incorporation_date',
        ),
        migrations.RenameField(
            model_name='tuitioncenter',
            old_name='incorpiration_date',
            new_name='incorporation_date',
        ),
    ]
