# Generated by Django 4.0.1 on 2022-12-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_user_icon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic_ext',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
