# Generated by Django 4.0.1 on 2022-08-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_set',
            field=models.BooleanField(default=True),
        ),
    ]
