# Generated by Django 4.0.1 on 2022-09-04 19:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_educator_organisation_affiliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='platform_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editor',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editor',
            name='certification',
            field=models.FileField(blank=True, upload_to='uploads/certification'),
        ),
        migrations.AddField(
            model_name='editor',
            name='example_work',
            field=models.FileField(blank=True, upload_to='uploads/examplework'),
        ),
        migrations.AddField(
            model_name='editor',
            name='writing_subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Other', 'Other')], default=[], max_length=89),
        ),
        migrations.AlterField(
            model_name='admin',
            name='specialised_subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Other', 'Other')], default=[], max_length=89),
        ),
        migrations.AlterField(
            model_name='educator',
            name='taught_subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Other', 'Other')], default=[], max_length=89),
        ),
        migrations.AlterField(
            model_name='student',
            name='studied_subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Other', 'Other')], default=[], max_length=89),
        ),
    ]
