# Generated by Django 4.0.1 on 2022-12-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_profile_pic_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic_ext',
            field=models.CharField(default=' ', max_length=10, null=True),
        ),
    ]
