service: basic-model
frameworkVersion: "3"

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2

functions:
  streamingChat:
    handler: index.handler
    url: true
    timeout: 120
    environment:
      OPEN_AI_API_KEY: ${env:OPEN_AI_API_KEY}
      OPEN_AI_ORGANISATION: ${env:OPEN_AI_ORGANISATION}

resources:
  extensions:
    StreamingChatLambdaFunctionUrl:
      Properties:
        InvokeMode: RESPONSE_STREAM
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - "POST"
          AllowHeaders:
            - "content-type"
