---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: eks-practicepractice
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: image-eks-practicepractice
        resources:
          requests:
            memory: "256Mi"   # Minimum memory required
            cpu: "100m"       # Minimum CPU required
          limits:
            memory: "512Mi"   # Maximum memory allowed
            cpu: "500m"       # Maximum CPU allowed
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: website
        command: ["apache2ctl", "-D", "FOREGROUND"]
