---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: eks-practicepractice
  labels:
    app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: amazonaws.com/eks-practicepractice
        ports:
        - containerPort: 80
          name: website
