---
apiVersion: v1
kind: Service
metadata:
  namespace: eks-practicepractice
  name: website
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
    - port: 433
      name: https
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: website

