---
apiVersion: v1
kind: Service
metadata:
    name: website
    namespace: eks-practicepractice
    labels:
        app: website
spec:
    type: LoadBalancer
    selector:
        app: website
    ports:
    - port: 80
      protocol: TCP  
      targetPort: 80
