---
apiVersion: v1
kind: Service
metadata:
    name: website
    namespace: eks-practicepractice
    labels:
        app: website
spec:
    type: LoadBalancer
    selector:
        app: website
    ports:
    - name: http
      port: 80
      protocol: TCP  
      targetPort: website
    - name: https
      port: 443
      protocol: TCP
      targetPort: website

